baseURL = 'https://dadalus.com'
languageCode = 'zh-cn'
title = "æ®µå°‘ğŸµDaDalus's Blog"
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowShareButtons = false

  # é¦–é¡µç›´æ¥æ˜¾ç¤ºæ–‡ç« åˆ—è¡¨
  disableSpecialSearchPages = true

  # åº•éƒ¨ç‰ˆæƒ
  [params.label]
    text = "æ®µå°‘ğŸµDaDalus's Blog"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/BinaryHB"

[params.footer]
  copyright = "@Cyborg Candidate"

[menu]
  [[menu.main]]
    identifier = "x"
    name = "ğ•"
    url = "https://x.com/BinaryHB"
    weight = 10
